### PR TITLE
Fix server deletion

### PR DESCRIPTION
**Pull request by BANanaD3V**
## Description of changes

Removed hash check that caused servers to delete

## CC Maintainers

@IogaMaster

### CODE REVIEW

**Comment by IogaMaster** [comment]
This was an intentional, or otherwise the servers wont update.

I can't really think of a better solution

**Comment by BANanaD3V** [comment]
> otherwise the servers wont update.

but they do? For me they update.

**Comment by BANanaD3V** [comment]
Can you try to update the server with my fork, but before updating it **change the hash** to the actual hash (i do it by setting it to `sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=` first and then to the correct one, but there must be a better way.

it works this way

**Comment by BANanaD3V** [comment]
Can we not rely on hash or not use it at all? I know its nix, but for such things as gameservers...

**Pull request merged**
